### ISSUE TITLE
Postcss

### ISSUE THREAD

**Issue by rodrigonehring** [monokrome/webpack-react-starter#1]
Do you need postcss if are using styled-components? Its a lot of dependencies with can be removed...

**Comment by monokrome** [comment]
Hi, @rodrigonehring! Thanks for posting this issue! :)

I think that `styled-components` uses postcss, so this allows us to do proper vendor prefixing and support newer CSS features w/ older browser support.

It's possible that I misunderstand! What do you think?

**Comment by mxstbr** [comment]
`styled-components` doesn't use PostCSS anymore since v2. (only on ReactNative) We wrote our own super tiny and fast parser called stylis!

On top of that, you can kick that out of your bundle with the Babel plugin by enabling the (experimental for now) option `preprocess: true`, which parses your CSS at build time. :muscle:

**Comment by monokrome** [comment]
Awesome! Thanks to both of you for clarifying this! I've pushed a commit that removes all the CSS excess :)

**Comment by monokrome** [comment]
Also, of course, I hope you feel free to reopen the issue (or send a pull request) if this isn't fixed :) :) :)
